DOCKER_IMAGE_NAME = <%=config[:constant_name].downcase%>

build:
	docker build -t ${USER}/${DOCKER_IMAGE_NAME} .

# If you have to configure volumes, do that from here
# configure:

run:
	(docker start ${DOCKER_IMAGE_NAME}) || \
	docker run --name ${DOCKER_IMAGE_NAME} -d ${USER}/${DOCKER_IMAGE_NAME}

console:
	docker run -it \
  -e an_env_var=${HIDDEN_ENV} \
  ${USER}/${DOCKER_IMAGE_NAME} bash

.PHONY: build
